default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PGSQL_USERNAME"] %>
  password: <%= ENV["PGSQL_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: owaycodeinterview